### ISSUE TITLE
Panic in rows.Next()

### ISSUE THREAD

**Issue by crosslogic** [MonetDB/MonetDB-Go#2]
I'm doing a simple: 
```
rows, err := s.DB.Query("SELECT * FROM accounts;")
	if err != nil {
		panic(err)
	}
	defer rows.Close()

	for rows.Next() { // PANIC HERE
		
	}
```
There is one row with 3 columns.
The Row struct has it's data right, but rows field is nil.

```
  query: (string) (len=23) "SELECT * FROM accounts;",
  execId: (int) 0,
  lastRowId: (int) 0,
  rowCount: (int) 1,
  queryId: (int) 0,
  offset: (int) 0,
  columnCount: (int) 3,
  rows: ([][]driver.Value) <nil>,
```

Any idea?

**Comment by MitchellWeg** [comment]
Can you be a little bit more specific on the panic you're getting?

I've rewritten your example a little bit as follows:

```go
package main

import (
	"database/sql"

	_ "github.com/MonetDB/MonetDB-Go/src"
)

func main() {
	db, err := sql.Open("monetdb", "monetdb:monetdb@[::1]:50000/demo")

	if err != nil {
		panic(err)
	}

	defer db.Close()

	rows, err := db.Query("SELECT * FROM foo;")
	if err != nil {
		panic(err)
	}
	defer rows.Close()

	for rows.Next() { // PANIC HERE
	}
}

```
Where `foo` has 3 columns: `bar, baz, temp`
and I don't encounter any problems. Not from Go itself, or the server.

**Comment by crosslogic** [comment]
It's happening because one column is NULL. Try again your example with 
```sql
UPDATE foo SET temp = NULL;
```

main.go

```go
import (
	"database/sql"

	_ "github.com/MonetDB/MonetDB-Go/src"
)

func main() {
	db, err := sql.Open("monetdb", "monetdb:monetdb@[::1]:50000/cash")

	if err != nil {
		panic(err)
	}

	defer db.Close()

	rows, err := db.Query("SELECT * FROM accounts;")
	if err != nil {
		panic(err)
	}
	defer rows.Close()

	for rows.Next() { // PANIC HERE
	}
}
```


go.mod
```go
module bitbucket.org/marcos19/monettest

go 1.17

require github.com/MonetDB/MonetDB-Go v1.0.0

```

go version
`go version go1.17 linux/amd64`

Error
```
marcos@LAPTOP-IBLORM5U:~/go/src/bitbucket.org/marcos19/monettest$ go run main.go
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/MonetDB/MonetDB-Go/src.(*Rows).Next(0xc00011e120, {0xc00007ccc0, 0x3, 0x0})
        /home/marcos/go/pkg/mod/github.com/!monet!d!b/!monet!d!b-!go@v1.0.0/src/rows.go:77 +0x238
database/sql.(*Rows).nextLocked(0xc000138400)
        /usr/local/go/src/database/sql/sql.go:2967 +0x111
database/sql.(*Rows).Next.func1()
        /usr/local/go/src/database/sql/sql.go:2945 +0x2f
database/sql.withLock({0x5679d8, 0xc000138430}, 0xc000157ec0)
        /usr/local/go/src/database/sql/sql.go:3396 +0x8c
database/sql.(*Rows).Next(0xc000138400)
        /usr/local/go/src/database/sql/sql.go:2944 +0x6f
main.main()
        /home/marcos/go/src/bitbucket.org/marcos19/monettest/main.go:24 +0xe9
exit status 2
```

mclient query:
```
sql>select * from accounts;
+------+------+--------+
| id   | name | parent |
+======+======+========+
|    1 | Caja |   null |
+------+------+--------+
1 tuple
```

**Comment by crosslogic** [comment]
Any progress about this issue?

**Comment by MitchellWeg** [comment]
I've pinpointed the issue, yet I have some different priorities and was not yet able to push a fix. I haven't forgotten it though, and hope to fix this issue asap.

**Comment by MitchellWeg** [comment]
I pushed a fix for this, and now it works on my machine. Can you check if it also fixes it for you?
